version: '3.4'

services:
  eshop:
    container_name: eshop
    build:
      context: .
      dockerfile: eShop/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - "eshop_network"

  eshop-database:
    image: postgres
    container_name: eshop-database
    environment:
      - POSTGRES_DB=eShop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty1234
    volumes:
      - ./.containers/eshop-database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - "eshop_network"

networks:
  eshop_network:
    driver: bridge